name: 4. ブランチの push の時の成果物をダウンロード可能にする

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # ビルド処理に置き換える
      - run: |
          touch artifact
          zip artifact.zip artifact

      - name: Upload build artifact
        # タグ以外が push された場合のみ実行される
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v1
        with:
          # 表示名 (必須)
          name: artifact.zip
          # アップロードするファイルまたはディレクトリ (必須)
          path: ./artifact

      - uses: actions/create-release@master
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: 4. ブランチの push の時の成果物をダウンロード可能にする
          body: |
            リリースの作成テストです。
            下書きかつプレリリースの状態で作成されます。
          draft: true
          prerelease: true

      - uses: actions/upload-release-asset@master
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifact.zip
          asset_name: artifact.zip
          asset_content_type: application/zip
